export const data = {
  message: 'success',
  data: {
    _id: '65c0dc5261ce6b8539e57744',
    phone_number_id: '100609346426084',
    conversations: [
      {
        phone_number: '237670142491',
        chat_messages: [
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Hi\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Hi\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Hi\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Hi\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Hi\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Hi\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'What is your name ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Ben',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Your age ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: '50',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Hi\n\nsend: What is your name ?\nreceive: Ben\n\nsend: Your age ?\nreceive: 50\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'What is your name ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Your age ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: '10',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Hi\n\nsend: What is your name ?\nreceive: Hi\n\nsend: Your age ?\nreceive: 10\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Assistance ménagère. Nos produits ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Marmites',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Catégorie ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Marmite chauffante',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Assistance ménagère. Nos produits ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Gaz domestique',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Quantité ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: '18 Kg',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Livraison à domicile ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Non',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'Votre numéro de téléphone ?',
            is_bot: true,
            is_admin: false,
          },
          {
            text: '345667778',
            is_bot: false,
            is_admin: false,
          },
          {
            text: 'send: ...\nreceive: Marmite chauffante\n\nsend: Assistance ménagère. Nos produits ?\nreceive: Gaz domestique\n\nsend: Quantité ?\nreceive: 18 Kg\n\nsend: Livraison à domicile ?\nreceive: Non\n\nsend: Votre numéro de téléphone ?\nreceive: 345667778\n\n',
            is_bot: true,
            is_admin: false,
          },
          {
            text: 'Hi',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T10:09:13.832Z',
          },
          {
            text: 'Assistance ménagère. Nos produits ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T10:09:14.884Z',
          },
        ],
      },
      {
        phone_number: '237666167464',
        chat_messages: [
          {
            text: 'Hello',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:15:53.604Z',
          },
          {
            text: 'Assistance ménagère. Nos produits ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:15:54.409Z',
          },
          {
            text: 'Marmites',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:15:59.006Z',
          },
          {
            text: 'Catégorie ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:15:59.517Z',
          },
          {
            text: 'Marmite ordinaire',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:16:04.437Z',
          },
          {
            text: 'Contenance ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:16:04.902Z',
          },
          {
            text: '10L',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:16:08.306Z',
          },
          {
            text: 'Nom du quartier ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:16:08.825Z',
          },
          {
            text: 'Carrière',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:16:15.612Z',
          },
          {
            text: 'Votre numéro de téléphone ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:16:16.125Z',
          },
          {
            text: '656436173',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:16:28.133Z',
          },
          {
            text: 'send: ...\nreceive: Hello\n\nsend: Assistance ménagère. Nos produits ?\nreceive: Marmites\n\nsend: Catégorie ?\nreceive: Marmite ordinaire\n\nsend: Contenance ?\nreceive: 10L\n\nsend: Nom du quartier ?\nreceive: Carrière\n\nsend: Votre numéro de téléphone ?\nreceive: 656436173\n\n',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:16:28.149Z',
          },
          {
            text: 'Hello',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:25:04.606Z',
          },
          {
            text: 'Assistance ménagère. Nos produits ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:25:05.397Z',
          },
          {
            text: 'Gaz domestique',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:25:12.792Z',
          },
          {
            text: 'Quantité ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:25:13.255Z',
          },
          {
            text: '18 Kg',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:25:16.535Z',
          },
          {
            text: 'Livraison à domicile ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:25:16.972Z',
          },
          {
            text: 'Oui',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:25:22.014Z',
          },
          {
            text: 'Nom du quartier ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:25:22.434Z',
          },
          {
            text: 'Tsinga',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:25:28.637Z',
          },
          {
            text: 'Votre numéro de téléphone ?',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:25:29.088Z',
          },
          {
            text: '620830191',
            is_bot: false,
            is_admin: false,
            date: '2024-02-08T12:25:43.022Z',
          },
          {
            text: 'send: ...\nreceive: Hello\n\nsend: Assistance ménagère. Nos produits ?\nreceive: Gaz domestique\n\nsend: Quantité ?\nreceive: 18 Kg\n\nsend: Livraison à domicile ?\nreceive: Oui\n\nsend: Nom du quartier ?\nreceive: Tsinga\n\nsend: Votre numéro de téléphone ?\nreceive: 620830191\n\n',
            is_bot: true,
            is_admin: false,
            date: '2024-02-08T12:25:43.035Z',
          },
        ],
      },
    ],
  },
};